### ISSUE TITLE
Add `coverage` column to csv files for chart 5 and 6 

### ISSUE THREAD

**Issue by Aeilert** [PIP-Technical-Team/pipaux#75]
Hi @congminh6, 

In order to be consistent on the Country Profiles page I think it will be useful to add a label with Reporting level / survey coverage for all of the six charts. We already added a fix for the two poverty charts in pipapi, but for the four other charts the easiest would be if the `coverage` column existed in the raw .csv files. For charts 3 and 4 this is already the case, but it is not present for chart 5 and 6. Would it be possible to add it there? That is to `indicator_values_country_chart6_KI4.csv` and `indicator_values_country_chart5.csv`. 

cc:  @tonyfujs, @randrescastaneda

**Comment by congminh6** [comment]
Many thanks Aleksander. Yes, we can merge m:1 (code year surveyed, datatype) based on the price framework to bring in the coverage information.
Copy @Haoyu ***@***.***>, so we will do it accordingly in GMI/output for PIP. @Haoyu ***@***.***>: Do you have Github account so we can link?

Best,
Minh

From: Aeilert ***@***.***>
Sent: Monday, March 7, 2022 7:41 AM
To: PIP-Technical-Team/pipaux ***@***.***>
Cc: Minh Cong Nguyen ***@***.***>; Mention ***@***.***>
Subject: [PIP-Technical-Team/pipaux] Add `coverage` column to csv files for chart 5 and 6 (Issue #75)

[External]

Hi @congminh6<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcongminh6&data=04%7C01%7Cmnguyen3%40worldbank.org%7C0a8c0c77c38a47363bf408da0037c569%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822536776810057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rFizY95AHCGZ%2FUyNbeDmaKJdPSKxjfy3PJuLVgFwGbY%3D&reserved=0>,

In order to be consistent on the Country Profiles page I think it will be useful to add a label with Reporting level / survey coverage for all of the six charts. We already added a fix for the two poverty charts in pipapi, but for the four other charts the easiest would be if the coverage column existed in the raw .csv files. For charts 3 and 4 this is already the case, but it is not present for chart 5 and 6. Would it be possible to add it there? That is to indicator_values_country_chart6_KI4.csv and indicator_values_country_chart5.csv.

cc: @tonyfujs<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftonyfujs&data=04%7C01%7Cmnguyen3%40worldbank.org%7C0a8c0c77c38a47363bf408da0037c569%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822536776810057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=K9n8abUAifhGnNuuABg8gx2G1F9fR2Cfdf34V835CUU%3D&reserved=0>, @randrescastaneda<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frandrescastaneda&data=04%7C01%7Cmnguyen3%40worldbank.org%7C0a8c0c77c38a47363bf408da0037c569%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822536776810057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SF4i3CI%2B9sZwOgtkZ%2Fd9jAy2r2xe%2BhI2QSOy8XbeURU%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPIP-Technical-Team%2Fpipaux%2Fissues%2F75&data=04%7C01%7Cmnguyen3%40worldbank.org%7C0a8c0c77c38a47363bf408da0037c569%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822536776810057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=L1X10ydFOaA7iZ2F%2BZeSiouFR6fuWvjK2NIaqKjj%2BFk%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEN66L42ZY6T2ES253H5I6DU6X2OXANCNFSM5QDFTSGQ&data=04%7C01%7Cmnguyen3%40worldbank.org%7C0a8c0c77c38a47363bf408da0037c569%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822536776810057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GHc8%2FVR5rdV6gbXylC8eWMw%2FqQgK1R830zEFTF6MrLQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmnguyen3%40worldbank.org%7C0a8c0c77c38a47363bf408da0037c569%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822536776810057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Ipm5aHI3%2BeMHCkAgk%2F1IdqsqOMwA%2FrnmN2OiDaVXMb0%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmnguyen3%40worldbank.org%7C0a8c0c77c38a47363bf408da0037c569%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822536776810057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v9PbOlfk7YHTraDbpeD7fGKMMVJniNM1gGpOQvuyIsQ%3D&reserved=0>.

**Comment by congminh6** [comment]
Hi Minh,

My github account is: hwwbg

Best,
Haoyu

From: Minh Cong Nguyen ***@***.***>
Sent: Monday, March 7, 2022 8:45 AM
To: PIP-Technical-Team/pipaux ***@***.***>; PIP-Technical-Team/pipaux ***@***.***>; Haoyu Wu ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [PIP-Technical-Team/pipaux] Add `coverage` column to csv files for chart 5 and 6 (Issue #75)

Many thanks Aleksander. Yes, we can merge m:1 (code year surveyed, datatype) based on the price framework to bring in the coverage information.
Copy @Haoyu ***@***.***>, so we will do it accordingly in GMI/output for PIP. @Haoyu ***@***.***>: Do you have Github account so we can link?

Best,
Minh

From: Aeilert ***@***.******@***.***>>
Sent: Monday, March 7, 2022 7:41 AM
To: PIP-Technical-Team/pipaux ***@***.******@***.***>>
Cc: Minh Cong Nguyen ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [PIP-Technical-Team/pipaux] Add `coverage` column to csv files for chart 5 and 6 (Issue #75)

[External]

Hi @congminh6<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcongminh6&data=04%7C01%7Cmnguyen3%40worldbank.org%7C0a8c0c77c38a47363bf408da0037c569%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822536776810057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rFizY95AHCGZ%2FUyNbeDmaKJdPSKxjfy3PJuLVgFwGbY%3D&reserved=0>,

In order to be consistent on the Country Profiles page I think it will be useful to add a label with Reporting level / survey coverage for all of the six charts. We already added a fix for the two poverty charts in pipapi, but for the four other charts the easiest would be if the coverage column existed in the raw .csv files. For charts 3 and 4 this is already the case, but it is not present for chart 5 and 6. Would it be possible to add it there? That is to indicator_values_country_chart6_KI4.csv and indicator_values_country_chart5.csv.

cc: @tonyfujs<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftonyfujs&data=04%7C01%7Cmnguyen3%40worldbank.org%7C0a8c0c77c38a47363bf408da0037c569%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822536776810057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=K9n8abUAifhGnNuuABg8gx2G1F9fR2Cfdf34V835CUU%3D&reserved=0>, @randrescastaneda<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frandrescastaneda&data=04%7C01%7Cmnguyen3%40worldbank.org%7C0a8c0c77c38a47363bf408da0037c569%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822536776810057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SF4i3CI%2B9sZwOgtkZ%2Fd9jAy2r2xe%2BhI2QSOy8XbeURU%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPIP-Technical-Team%2Fpipaux%2Fissues%2F75&data=04%7C01%7Cmnguyen3%40worldbank.org%7C0a8c0c77c38a47363bf408da0037c569%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822536776810057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=L1X10ydFOaA7iZ2F%2BZeSiouFR6fuWvjK2NIaqKjj%2BFk%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEN66L42ZY6T2ES253H5I6DU6X2OXANCNFSM5QDFTSGQ&data=04%7C01%7Cmnguyen3%40worldbank.org%7C0a8c0c77c38a47363bf408da0037c569%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822536776810057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GHc8%2FVR5rdV6gbXylC8eWMw%2FqQgK1R830zEFTF6MrLQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmnguyen3%40worldbank.org%7C0a8c0c77c38a47363bf408da0037c569%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822536776810057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Ipm5aHI3%2BeMHCkAgk%2F1IdqsqOMwA%2FrnmN2OiDaVXMb0%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmnguyen3%40worldbank.org%7C0a8c0c77c38a47363bf408da0037c569%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822536776810057%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v9PbOlfk7YHTraDbpeD7fGKMMVJniNM1gGpOQvuyIsQ%3D&reserved=0>.

**Comment by hwwbg** [comment]
Hi @congminh6  and @Aeilert 

Do you prefer to have this done asap or wait for my next update from GMI? It will be around March 20th. 

Thanks!
Best,
Haoyu

**Comment by congminh6** [comment]
Hi Haoyu,

I think if we can do now so ITS can put it in so we can test data ingestion and UI. Then by March 18 (not 20) we send the final data just to refresh.

Best,
Minh

Sent from my iPhone

On Mar 7, 2022, at 10:18 AM, Haoyu Wu ***@***.***> wrote:

﻿ [External]

Hi @congminh6<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcongminh6&data=04%7C01%7Cmnguyen3%40worldbank.org%7C8fd042e55df24d47a1dc08da004dbb5b%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822631105370722%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yr%2BX4vWuiV79yGjsDGPRcSFCnxwhwAz6g0gUlCCUras%3D&reserved=0> and @Aeilert<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAeilert&data=04%7C01%7Cmnguyen3%40worldbank.org%7C8fd042e55df24d47a1dc08da004dbb5b%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822631105370722%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IXkjGtFZNCG7YWbzwMxlAd9I4jQMw56gVBfMh4fQMY8%3D&reserved=0>

Do you prefer to have this done asap or wait for my next update from GMI? It will be around March 20th.

Thanks!
Best,
Haoyu

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPIP-Technical-Team%2Fpipaux%2Fissues%2F75%23issuecomment-1060800388&data=04%7C01%7Cmnguyen3%40worldbank.org%7C8fd042e55df24d47a1dc08da004dbb5b%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822631105370722%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ylKhWjnh1siHrh8TEdn%2FWvBBCRmO6O1MBCDA3KiXkNM%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEN66LYAM3T4W6NPHEFQEHDU6YM4HANCNFSM5QDFTSGQ&data=04%7C01%7Cmnguyen3%40worldbank.org%7C8fd042e55df24d47a1dc08da004dbb5b%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822631105526951%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ybeuzvzcjIy23wkhcKAlBY4KV28Sen%2F4idhJ5459JaU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmnguyen3%40worldbank.org%7C8fd042e55df24d47a1dc08da004dbb5b%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822631105526951%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HQvW6y%2B%2F9GTjkrbCFS5nkhQ2oazl%2FpJh373%2F25IZ5J8%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmnguyen3%40worldbank.org%7C8fd042e55df24d47a1dc08da004dbb5b%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C637822631105526951%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sTjB5AA%2B45iTlEcdL3bFEVruXzw00WXjof1DmOTdLvA%3D&reserved=0>.

**Comment by Aeilert** [comment]
Thanks Minh, Hayou

Yes I would prefer asap, since then we can start incorporating this on the UI side.

/AE

**Comment by hwwbg** [comment]
Please find the two datasets with coverage attached. Kindly note that all the data are from AM2021
[indicator_values_country_chart5.csv](https://github.com/PIP-Technical-Team/pipaux/files/8199840/indicator_values_country_chart5.csv)
[indicator_values_country_chart6_KI4.csv](https://github.com/PIP-Technical-Team/pipaux/files/8199841/indicator_values_country_chart6_KI4.csv)
.

**Comment by Aeilert** [comment]
Thanks Hayou!
